### ISSUE TITLE
LSprite 應該 public，或是？

### ISSUE THREAD

**Issue by MontyPan** [DontCareAbout/GF#8]
當初不讓這個 interface 是 public，主要是擔心如果有人亂實作會導致奇怪的後果。（謎之聲：誰沒事會去自己弄一個出來？弄出來有問題自己負責阿 [指]）

但是現在發現 `LSprite` 如果不是 public interface，那麼 `Layer.getMembers()` 對 caller 而言沒有任何意義。這也導致了「要移除所有 member」無法作到、不然就是 sub class 自己再維護一份 member list（謎之聲：WTF）。

所以，似乎有兩個選項：

1. `LSprite` 改為 public interface
1. `Layer.getMembers()` 改為 default level

不管選哪一個，`Layer` 都應該提供「移除所有 member」的 method...... [遠目]

**Comment by jay-gu** [comment]
interface 不就是要讓人實做的?
現在很少人用abstract class +abstract 強迫實作吧,尤其是java 8以後

**Comment by MontyPan** [comment]
依照你的 comment，所以你是支持選項 1？

------

接下來好像有點岔題了（謎之聲：有主題過嗎？），不過好像值得討論一下。

access level 的設計我認為其中一個本質就是提供保護機制，這可以讓 library 不容易被改寫、行為也不容易被改變，設計的好的話也許可以加強 robust。

當然這保護機制不是絕對的，field / method 可以透過 reflection 硬上，class 則是 library user 在自己的 source code 弄一個同樣 package 的目錄，然後弄一個 public class 繼承......

先不管惡搞的作法，回到「interface 不就是要讓人實做的?」這句話，那麼我覺得可以是「讓 library developer 實作」而不是「讓 library user 實作」。

至於 abstract class，我個人認為是還是有存在的必要，尤其是針對 lightweight library（或是說：預設沒有 DI / IoC）應該還蠻有用的（以我的智商看來 💃 ）。Java 8 對 interface 的改變只是提供 default / static method 的實作能力，但是沒辦法讓 interface 有 field 吧？

----

快點投票（？），我要來改版了 [敲碗]

**Comment by jay-gu** [comment]
1
